version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sa_pwd
      MYSQL_DATABASE: portal
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa_pwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
